### ISSUE TITLE
Clarity on MT-Bench scores

### ISSUE THREAD

**Issue by BBQGOD** [pldlgb/nuggets#3]
Could you give a detailed explanation on the MT-bench scores? Specifically, are you using the score from first turn or the average of turn 1 & 2? If the latter is the case, it seems your baseline `Alpaca_full` has already demonstrated better performance than Alpaca 13b, which is quite interesting.

**Comment by pldlgb** [comment]
Since the Alpaca instruction dataset itself only contains single-turn Q&A, we only assessed the results of Turn 1 in MT-bench. It was an oversight on our part not to make this clear in the paper. We will clarify the evaluation of the MT-Score in future versions of the paper. Thank you for your correction.

**Comment by BBQGOD** [comment]
Thanks~
